### ISSUE TITLE
Feature proposal: All Available configuration options via Query String

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#30]
As same as `platformSettings.textureMode` but for all options.
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/settings
Useful for rapid tries in development.
Regards

**Comment by michielvandergeest** [comment]
In SDK 2.* we have moved all options to a dedicated settings.json file because it's more versatile and can easily be shared / checked into repo. The only exception is the `textureMode` setting, that can be configured / overwritten in the URL. This is a legacy support thing.

If you use the watcher in the Lightning-CLI, the project will automatically rebuild if you change something in your `settings.json`
