### ISSUE TITLE
Custom id attribute when inspector is enabled

### ISSUE THREAD

**Issue by lewispeel** [WebPlatformForEmbedded/Lightning-SDK#67]
Hi,

I'm using Cypress.io to run my end-to-end tests and would like to be able to specify a custom value for the `id` attribute when the inspector is enabled. Currently this is a number generated by Lightning.

Possible solution...

```
// support/lib/lightning-inspect.js
// add this to the Element prototype

Element.prototype.$customId = Element.prototype._customId;
  Object.defineProperty(Element.prototype, '_customId', {
    get: function () {
      return this.$customId;
    },
    set: function (v) {
      if (this.$customId !== v) {
        val(this, 'id', v, 0);
        this.$customId = v;
      }
    }
  });
```

```
// CustomComponent.js
// create a custom component with a setter for 'customId'

export default class Component extends lng.Component {
  static _template() {
    return {
      Background: {
        w: 1920, h: 1080,
        rect: true,
        color: 0xffCCFFFF,
      },
    };
  }
  set customId(v) {
    this._customId = v;
  }
}
```

```
// usage in app
// insert the custom component into the template with a custom id

import { Lightning } from 'wpe-lightning-sdk'
import CustomComponent from './CustomComponent'

export default class App extends Lightning.Component {
  static _template() {
    return {
      Foo: {
        customId: 'MY_CUSTOM_ID',
        type: CustomComponent,
      },
    }
  }
}
```

*EDIT* What would be even better is to have the custom id value integrated into `lng.Component`

**Comment by mattiapontonio** [comment]
I notice that exist a `ref` property that can be used with `childList.getByRef` method.
## Children
https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children
Think is kind of id.
I've Aldo notice that You cannot change id on `Element`.
So my solution for mapping my objects is to Elements is still under investigation.

### My personal impression
Seems to be good to not try to identify the components but architect them to be rebuilt and rerendered from top to bottom via setters. This approach seems to works in my experience. Kind of data-driven approach.

Mattia

**Comment by lewispeel** [comment]
Hi Mattia,

Isn't childList only accessible isn't Lightning? I'm using Cypress.io

**Comment by mattiapontonio** [comment]
Hi @lewispeel,

- I do not know Cypress.io
- Actually I do my test using `console.assert`, the debugger

in my experience (apologize if any errors):

- `childList` is a property accessible inside a `Component` if you're using Lightning-CLI + Lightning-SDK (suggested)
- `childList` is the way to access some safe methods in order to deal with children's of a component
- You cannot or is difficult to instantiate a `Component` out of the browser and out of an `Application` because they are dependent on the `canvas` element so dependent on the DOM and the browser.
- My advice: abstract business logic in serializable objects and classes like `Object`, `Array`, `Boolean`, `String` and do the test over them. Then provide a mapping logic-less to the Components using setter. Use Components only to manage event handling, patching of the graphic properties, etc.

Actually I do not know the Lightning-friendly way to do End-To-End test and seems is not yet documented.

Any other suggestions appreciated.
Best regards
Mattia

**Comment by lewispeel** [comment]
Hi Mattia,

Thanks for your suggestion. I know a few people who are successfully using Cypress.io to perform E2E tests and it looks promising.

I've since figured out a way that could work without the need for changing the id values. For this reason I'll be closing this issue.

**Comment by lewispeel** [comment]
I ended up using a combination the `type` and `ref` attributes exposed when running in inspect mode. Then in Cypress...  `cy.get('[type="Foo"]').get('[ref=Bar]').should('be.visible');`
